CREATE PROFILE "NORDEA_APPLICATION_PROFILE"LIMIT CPU_PER_SESSION DEFAULT
 CPU_PER_CALL DEFAULT
 CONNECT_TIME DEFAULT
 IDLE_TIME DEFAULT
 SESSIONS_PER_USER DEFAULT
 LOGICAL_READS_PER_SESSION DEFAULT
 LOGICAL_READS_PER_CALL DEFAULT
 PRIVATE_SGA DEFAULT
 COMPOSITE_LIMIT DEFAULT
 PASSWORD_LIFE_TIME UNLIMITED
 PASSWORD_GRACE_TIME DEFAULT
 PASSWORD_REUSE_MAX 15
 PASSWORD_REUSE_TIME 1
 PASSWORD_LOCK_TIME DEFAULT
 FAILED_LOGIN_ATTEMPTS 50
 PASSWORD_VERIFY_FUNCTION NULL;