CREATE USER "Z883612" IDENTIFIED BY Dont4Get DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
  /
CREATE USER "Z663303" IDENTIFIED BY Dont4Get DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
  /
CREATE USER "Z651358" IDENTIFIED BY Dont4Get DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
  /
CREATE USER "Z190207" IDENTIFIED BY Dont4Get DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
  /
CREATE OR REPLACE VIEW AMACCOUNTPOSTING (
  FUNCTION, TRANSACTIONTYPE, TRANSACTIONCODE, CORRECTIONCODE, VALUEDAY, PAYMENTDAY, BOOKINGDAY, ARCHIVECODE, ACCOUNTNUMBER, ACCOUNTCURRENCY, DEBITCREDIT, BOOKINGPARTYAGENTID, AMOUNT, ACCOUNTNAME, TRANSACTIONDETAILSKEYTYPE, INTERNALACCOUNTIDENTIFIER, CUSTOMERMESSAGETEXT, REFERENCETYPE, CUSTOMERMESSAGETYPE, TRANSACTIONRETURNCODE, TRANSACTIONRETURNCODETEXT, ORIGINALLEGACYRETURNCODE, BOOKINGID, POSTINGTYPE, STATUS, VERSION, WHENMODIFIED, SOURCECODE, COUNTERACCOUNTNAME, COUNTERBOOKINGPARTYAGENTID, ACCOUNTSOURCE, ACCOUNTTYPE, ARCHIVECODEORIGINAL, AUTORESENDCOUNTER, FREEMESSAGETEXT, CUSTOMERNUMBER, TRANSACTIONRETURNCODETYPE, CATEGORY, TIMESTAMP, RESPONSESINCELASTRESEND, TRANSACTIONFORCINGCODE)
AS
  SELECT FUNCTION,
    TRANSACTIONTYPE,
    TRANSACTIONCODE,
    CORRECTIONCODE,
    VALUEDAY,
    PAYMENTDAY,
    BOOKINGDAY,
    ARCHIVECODE,
    ACCOUNTNUMBER,
    ACCOUNTCURRENCY,
    DEBITCREDIT,
    BOOKINGPARTYAGENTID,
    AMOUNT,
    ACCOUNTNAME,
    TRANSACTIONDETAILSKEYTYPE,
    INTERNALACCOUNTIDENTIFIER,
    CUSTOMERMESSAGETEXT,
    REFERENCETYPE,
    CUSTOMERMESSAGETYPE,
    TRANSACTIONRETURNCODE,
    TRANSACTIONRETURNCODETEXT,
    ORIGINALLEGACYRETURNCODE,
    BOOKINGID,
    POSTINGTYPE,
    STATUS,
    VERSION,
    WHENMODIFIED,
    SOURCECODE,
    COUNTERACCOUNTNAME,
    COUNTERBOOKINGPARTYAGENTID,
    ACCOUNTSOURCE,
    ACCOUNTTYPE,
    ARCHIVECODEORIGINAL,
    AUTORESENDCOUNTER,
    FREEMESSAGETEXT,
    CUSTOMERNUMBER,
    TRANSACTIONRETURNCODETYPE,
    CATEGORY,
    TIMESTAMP,
    RESPONSESINCELASTRESEND,
    TRANSACTIONFORCINGCODE
  FROM BPHADMIN.ACCOUNTPOSTING ;
  /
CREATE OR REPLACE VIEW BPHADMIN.AMBLACKLIST(BLACKLISTRECORDKEY, VERSION, WHENMODIFIED, ENDORSESTATUS, BANKKEY, BANKGROUPID, CREDITPARTYAGENTID, CREDITPARTYID, PROCESSINGSCHEME, CREDITPARTYAGENTCTRYCODE, OUTCOME)
AS
  SELECT BLACKLISTRECORDKEY,
    VERSION,
    WHENMODIFIED,
    ENDORSESTATUS,
    BANKKEY,
    BANKGROUPID,
    CREDITPARTYAGENTID,
    CREDITPARTYID,
    PROCESSINGSCHEME,
    CREDITPARTYAGENTCTRYCODE,
    OUTCOME
  FROM BPHADMIN.BLACKLIST ;
  /
CREATE OR REPLACE VIEW BPHADMIN.AMBLACKLIST_D( BLACKLISTRECORDKEY, VERSION, WHENMODIFIED, ENDORSESTATUS, BANKKEY, BANKGROUPID, CREDITPARTYAGENTID, CREDITPARTYID, PROCESSINGSCHEME, CREDITPARTYAGENTCTRYCODE, OUTCOME, WHENDELETED)
AS
  SELECT BLACKLISTRECORDKEY,
    VERSION,
    WHENMODIFIED,
    ENDORSESTATUS,
    BANKKEY,
    BANKGROUPID,
    CREDITPARTYAGENTID,
    CREDITPARTYID,
    PROCESSINGSCHEME,
    CREDITPARTYAGENTCTRYCODE,
    OUTCOME,
    WHENDELETED
  FROM BPHADMIN.BLACKLIST_D ;
  /
CREATE OR REPLACE VIEW BPHADMIN.AMPAYMENTTRANSACTION(PAYMENTTRANSACTIONKEY, INCOMINGTRANSACTIONGROUPKEY, OUTGOINGTRANSACTIONGROUPKEY, INCOMINGINSTRUCTIONKEY, OPICKEY, BANKGROUPID, BANKKEY, OUTGINTCHGCLEARINGCNDTNKEY, OUTGINSTRSETTLEMENTPRTCPNTKEY, OUTGINSTRBUSINESSPRTCPNTKEY, REJECTRECONCILIATIONKEY, CANCELRECONCILIATIONKEY, DISPLAYTRANSACTIONID, STATUS, VERSION, WHENMODIFIED, CLASSIFICATIONIDX, ENDTOENDIDIDX, FIRSTINSTRUCTINGAGENTTRNIDIDX, SETTLEMENTAMOUNTIDX, SETTLEMENTCURRENCYIDX, INCOMINGSETTLEMENTDAYIDX, SETTLEMENTDAYIDX, DEBITCREDITINDICATORIDX, PROCESSINGSCHEMEIDX, INSTRUCTEDDAYIDX, RTRANSACTIONQUALIFICATIONIDX, ORIGINALENDTOENDIDIDX, PRIORITYIDX, DEBITPARTYAGENT2IDIDX, DEBITPARTYAGENT3IDIDX, DEBITPARTYAGENT4IDIDX, DEBITPARTYAGENT5IDIDX, CREDITPARTYNAMEIDX, CREDITPARTYAGENTIDIDX, CREDITPARTYAGENT2IDIDX, CREDITPARTYAGENT3IDIDX, CREDITPARTYAGENT4IDIDX, CREDITPARTYAGENT5IDIDX, PROCESSINGDAYIDX, ONUSFLAGIPX, DUPLICATECHECKHASHIPX, UNROUTABLEFROMINSTRUCTIONIPX, OUTBOUNDIPX,
  OMITTEDFLAGIPX, RISKFILTERCHECKTIMESTAMPIPX, INSTRUCTINGAGENTTXNIDIDX, RTRANSACTIONFLAGIDX, RTRANSACTIONLEVELIDX, RTRANSACTIONPOSTSETLMNTFLAGIDX, RTRANSACTIONREFUNDFLAGIDX, ORIGFRSTINSTRUCTAGENTTXNIDIDX, SEQUENCETYPEIDX, DEBITPARTYIDIDX, MANDATEREFERENCEIDX, MANDATEAMENDMENTFLAGIDX, MANDATEKEY, CREDITPARTYSCHEMEPARTYIDIDX, VALIDATEDBYPARTICIPANTIDX, SETTLEDIDX, FOUREVADDITIONALREFUNDKEYIPX, TECHMANDATEREFERENCEIPX, TECHCRDTPRTYSCHMPRTYIDIPX, TECHCRDTPRTYSCHMPRTYIDTYPIPX, PRESETTLEMENTCANCELLEDIPX, REPRESENTATIONRECONCILTNIPX, MASSRELEASEDIDX, ISMIGRATIONPAYMENT)
AS
  SELECT PAYMENTTRANSACTIONKEY,
    INCOMINGTRANSACTIONGROUPKEY,
    OUTGOINGTRANSACTIONGROUPKEY,
    INCOMINGINSTRUCTIONKEY,
    OPICKEY,
    BANKGROUPID,
    BANKKEY,
    OUTGINTCHGCLEARINGCNDTNKEY,
    OUTGINSTRSETTLEMENTPRTCPNTKEY,
    OUTGINSTRBUSINESSPRTCPNTKEY,
    REJECTRECONCILIATIONKEY,
    CANCELRECONCILIATIONKEY,
    DISPLAYTRANSACTIONID,
    STATUS,
    VERSION,
    WHENMODIFIED,
    CLASSIFICATIONIDX,
    ENDTOENDIDIDX,
    FIRSTINSTRUCTINGAGENTTRNIDIDX,
    SETTLEMENTAMOUNTIDX,
    SETTLEMENTCURRENCYIDX,
    INCOMINGSETTLEMENTDAYIDX,
    SETTLEMENTDAYIDX,
    DEBITCREDITINDICATORIDX,
    PROCESSINGSCHEMEIDX,
    INSTRUCTEDDAYIDX,
    RTRANSACTIONQUALIFICATIONIDX,
    ORIGINALENDTOENDIDIDX,
    PRIORITYIDX,
    DEBITPARTYAGENT2IDIDX,
    DEBITPARTYAGENT3IDIDX,
    DEBITPARTYAGENT4IDIDX,
    DEBITPARTYAGENT5IDIDX,
    CREDITPARTYNAMEIDX,
    --CREDITPARTYACCOUNTIDX,
    CREDITPARTYAGENTIDIDX,
    CREDITPARTYAGENT2IDIDX,
    CREDITPARTYAGENT3IDIDX,
    CREDITPARTYAGENT4IDIDX,
    CREDITPARTYAGENT5IDIDX,
    PROCESSINGDAYIDX,
    ONUSFLAGIPX,
    DUPLICATECHECKHASHIPX,
    UNROUTABLEFROMINSTRUCTIONIPX,
    OUTBOUNDIPX,
    OMITTEDFLAGIPX,
    RISKFILTERCHECKTIMESTAMPIPX,
    INSTRUCTINGAGENTTXNIDIDX,
    RTRANSACTIONFLAGIDX,
    RTRANSACTIONLEVELIDX,
    RTRANSACTIONPOSTSETLMNTFLAGIDX,
    RTRANSACTIONREFUNDFLAGIDX,
    ORIGFRSTINSTRUCTAGENTTXNIDIDX,
    SEQUENCETYPEIDX,
    DEBITPARTYIDIDX,
    MANDATEREFERENCEIDX,
    MANDATEAMENDMENTFLAGIDX,
    MANDATEKEY,
    CREDITPARTYSCHEMEPARTYIDIDX,
    VALIDATEDBYPARTICIPANTIDX,
    SETTLEDIDX,
    FOUREVADDITIONALREFUNDKEYIPX,
    TECHMANDATEREFERENCEIPX,
    TECHCRDTPRTYSCHMPRTYIDIPX,
    TECHCRDTPRTYSCHMPRTYIDTYPIPX,
    PRESETTLEMENTCANCELLEDIPX,
    REPRESENTATIONRECONCILTNIPX,
    MASSRELEASEDIDX,
    ISMIGRATIONPAYMENT
  FROM BPHADMIN.PAYMENTTRANSACTION ;
  /
CREATE OR REPLACE VIEW BPHADMIN.AMREPORTBLOCKDETAIL(REPORTBLOCKDETAILKEY, REPORTBLOCKHEADERKEY, BODYTYPE, LINESEQUENCE, BLOCKSEQUENCE, VERSION, WHENMODIFIED)
AS
  SELECT REPORTBLOCKDETAILKEY,
    REPORTBLOCKHEADERKEY,
    BODYTYPE,
    LINESEQUENCE,
    BLOCKSEQUENCE,
    VERSION,
    WHENMODIFIED
  FROM BPHADMIN.REPORTBLOCKDETAIL ;
  /
CREATE OR REPLACE VIEW BPHADMIN.AMWORKLISTITEMKEY( WORKLISTITEMKEY, EVENTCODE, TARGETENTITYKEY, TARGETENTITYTYPE, TARGETENTITYDISPLAYID, PERSONID, PERSONNAME, DISPLAYIDENTIFIER, BANKKEY, BANKGROUPID, CREATIONDATETIME, CLAIMDATETIME, COMPLETIONDATETIME, STATUS,
  --NARRATIVE,
  INFORMATIONFLAG, VERSION, WHENMODIFIED, MSGDOMAIN, MSGNUMBER,
  /* TOKEN1,
  TOKEN2,
  TOKEN3,
  TOKEN4,
  TOKEN5,
  TOKEN6,
  TOKEN7,
  TOKEN8,
  TOKEN9,
  TOKEN10,
  MSGTEXT,*/
  PRIORITY, CATEGORY, REVIEWEES, EQUIVALENTAMOUNT, LATESTSUBMISSIONTIME, PAYMENTAMOUNT, PAYMENTCURRENCY, PAYMENTPRIORITYLEVEL, NEXTEVALUATIONTIMESTAMP, PAYMENTIMPORTANCE, WORKQUEUEKEY)
AS
  SELECT WORKLISTITEMKEY,
    EVENTCODE,
    TARGETENTITYKEY,
    TARGETENTITYTYPE,
    TARGETENTITYDISPLAYID,
    PERSONID,
    PERSONNAME,
    DISPLAYIDENTIFIER,
    BANKKEY,
    BANKGROUPID,
    CREATIONDATETIME,
    CLAIMDATETIME,
    COMPLETIONDATETIME,
    STATUS,
    --NARRATIVE,
    INFORMATIONFLAG,
    VERSION,
    WHENMODIFIED,
    MSGDOMAIN,
    MSGNUMBER,
    /* TOKEN1,
    TOKEN2,
    TOKEN3,
    TOKEN4,
    TOKEN5,
    TOKEN6,
    TOKEN7,
    TOKEN8,
    TOKEN9,
    TOKEN10,
    MSGTEXT,*/
    PRIORITY,
    CATEGORY,
    REVIEWEES,
    EQUIVALENTAMOUNT,
    LATESTSUBMISSIONTIME,
    PAYMENTAMOUNT,
    PAYMENTCURRENCY,
    PAYMENTPRIORITYLEVEL,
    NEXTEVALUATIONTIMESTAMP,
    PAYMENTIMPORTANCE,
    WORKQUEUEKEY
  FROM BPHADMIN.WORKLISTITEM ;
  /
  -- Create role BPH_READ_ROLE_RESTRICTED --
CREATE role BPH_READ_ROLE_RESTRICTED;
  /
  -- Grant table privs to BPH_READ_ROLE_RESTRICTED--
  GRANT
  SELECT ON BPHADMIN.VISSERVICEATTR TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VISSERVICEATTRDEFINITION TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VISSERVICEATTRDEFINITION_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VISSERVICEATTR_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WL_LLR_SOA_SERVER01 TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WL_LLR_SOA_SERVER02 TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WL_LLR_SOA_SERVER03 TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WL_LLR_SOA_SERVER04 TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WL_LLR_SOA_SERVER05 TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WL_LLR_SOA_SERVER06 TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WL_LLR_SOA_SERVER07 TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WL_LLR_SOA_SERVER08 TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WL_LLR_SOA_SERVER09 TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WL_LLR_SOA_SERVER10 TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WL_LLR_SOA_SERVER11 TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WL_LLR_SOA_SERVER12 TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WL_LLR_SOA_SERVER13 TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WL_LLR_SOA_SERVER14 TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WL_LLR_SOA_SERVER15 TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WL_LLR_SOA_SERVER16 TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WORKLISTITEM TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WORKQUEUE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WORKQUEUEMEMBER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.WORKQUEUEMEMBER_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVACUSTOMERPAYMENTTYPEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVACUSTOMERROLEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVACUSTOMERUSERFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVADASHBOARDFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAENDORSEMENTEVENTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAEXCHANGECONDITIONFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAEXCHANGEEVENTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAEXCHANGESCHEDULEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAGAVBANKBUSCALFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAGAVBLACKLISTBANKFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAGAVENDORSEMENTBANKFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAGAVEXCHANGEEVENTBANKFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAGAVEXCHCONDBUSCALFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAGAVMANDATEBANKFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAGAVPARTICIPANTBUSCALFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAGAVPARTICIPANTGROUPFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAGAVPROCPRODUCTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAGAVPROCSERVICEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAGAVVISPRODUCTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAGAVVISSERVICEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAGOPAYMENTORDERFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAINSTRTEMPLATEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAINTERNALACCOUNTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAMANDATEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAMANDATEFREQUENCYFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAPARAMPRODUCTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAPARAMSERVICEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAPARTICIPANTBANKDEPTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAPARTICIPANTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAPARTICIPANTGROUPFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAPARTICIPATIONDIRECTOFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAPAYMENTHISTORYFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAPAYMENTINSTRUCTIONFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAPAYMENTINTERCHANGEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAPAYMENTTRANSACTIONFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAPERSONFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAPROCAGREEMENTACCOUNTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAPROCAGREEMENTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAPROCPRODUCTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAPROCSERVICEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVARISKFILTERFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAROUTINGRULEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVASAVEDQUERYFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVASETTLEMENTTIMELINEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVASTOPORDERFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVATRNTEMPLATEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAVISAGREEMENTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAVISPRODUCTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAVISSERVICEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAWORKLISTITEMFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAWORKQUEUEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.COUNTERPARTY TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.COUNTERPARTY_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CPTPROCAGREEMENTACCOUNT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CPTPROCAGREEMENTACCOUNT_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTOMERDAP TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTOMERDAPENTITY TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTOMERDAPENTITY_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTOMERDAP_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTOMERFAP TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTOMERFAP_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTOMERFUNCTION TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTOMERFUNCTION_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTOMERPAYMENTTYPE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTOMERPAYMENTTYPE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTOMERROLE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTOMERROLE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTOMERUSER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTOMERUSERROLE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTOMERUSERROLE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTOMERUSER_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTPAYMENTTYPECOUNTERPARTY TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CUSTPAYMENTTYPECOUNTERPARTY_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CVAAUDITRECORDFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CVAAUTHORISATIONCLASSFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CVACUSTOMERPAYMENTTYPEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CVACUSTOMERROLEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CVACUSTOMERUSERFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CVADASHBOARDFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CVAENDORSEMENTEVENTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CVAPARTICIPANTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CVAPERSONFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CVAPROCAGREEMENTACCOUNTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CVAPROCAGREEMENTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CVAPROCPRODUCTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CVAPROCSERVICEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CVAVISAGREEMENTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CVAVISPRODUCTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.CVAVISSERVICEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.EBARECONCILIATION TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.EBASUBMISSION TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.EFFECTIVEPMTINSTRTMPLDETAILS TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.EFFECTIVEPMTINSTRTMPLDETAILS_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.EFFECTIVEPMTTRNTMPLDETAILS TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.EFFECTIVEPMTTRNTMPLDETAILS_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.ENDORSEMENTEVENT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.EXCHANGECONDITION TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.EXCHANGECONDITIONSCHEDULE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.EXCHANGECONDITIONSCHEDULE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.EXCHANGECONDITION_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.EXCHANGECRITERION TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.EXCHANGECRITERIONLITERAL TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.EXCHANGECRITERIONLITERAL_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.EXCHANGECRITERION_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.EXCHANGEEVENT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.EXCHANGESCHEDULE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.EXCHANGESCHEDULE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.GOPAYMENTORDER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.GOPAYMENTORDER_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.HOLIDAYDATE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.HOLIDAYDATE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.MANDATE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.MANDATEFREQUENCY TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.MANDATEPROCESSINGJOB TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.MASSACTIONDETAIL TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.MASSACTIONEVENT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VERSION_NDEA TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VISAGREEMENTSERVICE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VISAGREEMENTSERVICEATTR TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VISAGREEMENTSERVICEATTR_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VISAGREEMENTSERVICE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VISIBILITYAGREEMENT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VISIBILITYAGREEMENT_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VISIBILITYPRODUCT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VISIBILITYPRODUCT_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VISIBILITYSERVICE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VISIBILITYSERVICE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VISPRODUCTSERVICE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VISPRODUCTSERVICEATTR TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VISPRODUCTSERVICEATTR_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.VISPRODUCTSERVICE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.ACCOUNT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SAVEDQUERY TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SAVEDQUERYDETAIL TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SECAUTHENTICATION TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SECAUTHENTICATION_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SECPASSWORDHISTORY TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SECPASSWORDHISTORY_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SEQUENCER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SEQUENCERJOB TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SEQUENCERJOBTIMESTAMP TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SEQUENCERSERVER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SETTLEMENTTIMELINE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SETTLEMENTTIMELINEDETAIL TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SETTLEMENTTIMELINEDETAIL_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SETTLEMENTTIMELINE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SIGNATORY TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SIGNATORYGROUP TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SIGNATORYGROUP_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SIGNATORY_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.STOPORDER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.STOPORDERATTRIBUTE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.STOPORDERATTRIBUTE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.STOPORDER_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SWIFTBIC TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SWIFTCOUNTRY TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SWIFTCURRENCY TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SYNCHREQPROCESSINGJOB TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.SYSTEMPARAM TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCAGREEMENTACCOUNT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCAGREEMENTACCOUNT_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCAGREEMENTSERVICE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCAGREEMENTSERVICEATTR TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCAGREEMENTSERVICEATTR_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCAGREEMENTSERVICE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCESSINGAGREEMENT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCESSINGAGREEMENT_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCESSINGPRODUCT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCESSINGPRODUCT_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCESSINGSERVICE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCESSINGSERVICE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCPRODUCTSERVICE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCPRODUCTSERVICEATTR TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCPRODUCTSERVICEATTR_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCPRODUCTSERVICE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCSERVICEATTR TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCSERVICEATTRDEFINITION TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCSERVICEATTRDEFINITION_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PROCSERVICEATTR_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PURGELOG TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PURGETBL TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PURGETEMPTBL TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.RATES TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.REPORTBLOCKHEADER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.RISKFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.RISKFILTERCRITERION TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.RISKFILTERCRITERIONLITERAL TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.RISKFILTERCRITERIONLITERAL_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.RISKFILTERCRITERION_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.RISKFILTER_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.ROUTINGCRITERION TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.ROUTINGCRITERION_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.ROUTINGRULE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.ROUTINGRULE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.IBANPLUS TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.IBANPLUSSTAGING TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PARTICIPANT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PARTICIPANTGROUP TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PARTICIPANTGROUP_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PARTICIPANTPARTICIPANTGROUP TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PARTICIPANTPARTICIPANTGROUP_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PARTICIPANT_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PARTICIPATIONDIRECTORY TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PARTICIPATIONDIRECTORYSTAGING TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PARTICIPATIONDIRECTORY_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKUSER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKUSERROLE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKUSERROLE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKUSER_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANK_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BICPLUSIBAN TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BICPLUSIBANSTAGING TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BICPLUSIBAN_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BUSINESSCALENDAR TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BUSINESSCALENDAR_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BUSINESSHOUR TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BUSINESSHOUR_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAACCOUNTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAAUDITRECORDFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVAAUTHORISATIONCLASSFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVABANKDEPARTMENTFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVABANKFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVABANKINGRELATIONSHIPFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVABANKROLEFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVABANKUSERFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVABICPLUSIBANFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVABLACKLISTRECORDFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BVABUSINESSCALENDARFILTER TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PAYMENTINSTRUCTION TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PAYMENTINSTRUCTIONGROUP TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PAYMENTINSTRUCTIONTEMPLATE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PAYMENTINSTRUCTIONTEMPLATE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PAYMENTINSTRUCTIONTMPLTSTG TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.INTERFACINGMESSAGERECORD TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.INTERNALACCOUNT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.INTERNALENUMERATOR TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.ACCOUNT_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.AGENTCODE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.AGENTCODESTAGING TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.AGENTCODE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.AMSACCOUNT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.AUDITRECORD TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.AUTHORISATIONCLASS TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.AUTHORISATIONCLASS_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.AUTHORISATIONPROFILE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.AUTHORISATIONPROFILE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.AUTHORISATIONRULE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.AUTHORISATIONRULE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANK TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKCURRENCY TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKCURRENCY_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKDAP TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKDAPENTITY TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKDAPENTITY_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKDAP_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKDEPARTMENT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKDEPARTMENT_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKDIRECTORYPLUS TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKDIRECTORYPLUSSTAGING TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKFAP TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKFAP_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKFUNCTION TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKFUNCTION_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKGROUP TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKINGRELATIONSHIP TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKINGRELATIONSHIP_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKROLE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.BANKROLE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.INTERFACINGMESSAGE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.OPIC TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PARAMETERPRODUCT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PARAMETERSERVICE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PARAMPRODUCTSERVICE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PARAMPRODUCTSERVICEATTR TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PARAMSERVICEATTR TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PARAMSERVICEATTRDEFINITION TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.TEMPORARYFILEUPLOAD TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.TRANSPORTRECEIPT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.ACCOUNTINGEVENTPOSTING TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PAYMENTTRANSACTION TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PAYMENTTRANSACTIONGROUP TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PAYMENTTRANSACTIONTEMPLATE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PAYMENTTRANSACTIONTEMPLATE_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PERSON TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PERSON_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.INTERFACINGMESSAGEGROUP TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.INTERFACINGMESSAGEISSUE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.ACCOUNTINGEVENT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PAYMENTRECONCILIATION TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PAYMENTINTERCHANGE TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PAYMENTATTACHMENT TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.PAYMENTHISTORY TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.AMBLACKLIST TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.AMBLACKLIST_D TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.AMPAYMENTTRANSACTION TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.AMREPORTBLOCKDETAIL TO BPH_READ_ROLE_RESTRICTED;
  GRANT
  SELECT ON BPHADMIN.ACCOUNTPOSTING TO BPH_READ_ROLE_RESTRICTED;
  --User Z663303 --
  ALTER USER "Z663303" DEFAULT ROLE "BPH_READ_ROLE_RESTRICTED",
  "CONNECT";
  GRANT "BPH_READ_ROLE_RESTRICTED" TO Z663303;
  GRANT
CREATE SESSION TO "Z663303";
  audit ALL BY "Z663303" BY access;
  --User Z663303 --
  ALTER USER "Z651358" DEFAULT ROLE "BPH_READ_ROLE_RESTRICTED",
  "CONNECT";
  GRANT "BPH_READ_ROLE_RESTRICTED" TO Z651358;
  GRANT
CREATE SESSION TO "Z651358";
  audit ALL BY "Z651358" BY access;
  -- User Z190207 --
  ALTER USER "Z190207" DEFAULT ROLE "BPH_READ_ROLE_RESTRICTED",
  "CONNECT";
  GRANT "BPH_READ_ROLE_RESTRICTED" TO Z190207;
  GRANT
CREATE SESSION TO "Z190207";
  audit ALL BY "Z190207" BY access;
  -- User Z883612 --
  ALTER USER "Z883612" DEFAULT ROLE "BPH_READ_ROLE_RESTRICTED",
  "CONNECT";
  GRANT "BPH_READ_ROLE_RESTRICTED" TO Z883612;
  GRANT
CREATE SESSION TO "Z883612";
  audit ALL BY "Z883612" BY access;
  --Check if views is created.
  SELECT COUNT(*) FROM BPHADMIN.AMBLACKLIST;
  SELECT COUNT(*) FROM BPHADMIN.AMBLACKLIST_D;
  SELECT COUNT(*) FROM BPHADMIN.AMPAYMENTTRANSACTION;
  SELECT COUNT(*) FROM BPHADMIN.AMREPORTBLOCKDETAIL;
  SELECT COUNT(*) FROM BPHADMIN.AMACCOUNTPOSTING;
