CREATE OR REPLACE VIEW BPHADMIN.AMBLACKLIST_D( BLACKLISTRECORDKEY, VERSION, WHENMODIFIED, ENDORSESTATUS, BANKKEY, BANKGROUPID, CREDITPARTYAGENTID, CREDITPARTYID, PROCESSINGSCHEME, CREDITPARTYAGENTCTRYCODE, OUTCOME, WHENDELETED)
AS
  SELECT BLACKLISTRECORDKEY,
    VERSION,
    WHENMODIFIED,
    ENDORSESTATUS,
    BANKKEY,
    BANKGROUPID,
    CREDITPARTYAGENTID,
    CREDITPARTYID,
    PROCESSINGSCHEME,
    CREDITPARTYAGENTCTRYCODE,
    OUTCOME,
    WHENDELETED
  FROM BPHADMIN.BLACKLIST_D ;

quit;
