CREATE OR REPLACE VIEW BPHADMIN.AMBLACKLIST(BLACKLISTRECORDKEY, VERSION, WHENMODIFIED, ENDORSESTATUS, BANKKEY, BANKGROUPID, CREDITPARTYAGENTID, CREDITPARTYID, PROCESSINGSCHEME, CREDITPARTYAGENTCTRYCODE, OUTCOME)
AS
  SELECT BLACKLISTRECORDKEY,
    VERSION,
    WHENMODIFIED,
    ENDORSESTATUS,
    BANKKEY,
    BANKGROUPID,
    CREDITPARTYAGENTID,
    CREDITPARTYID,
    PROCESSINGSCHEME,
    CREDITPARTYAGENTCTRYCODE,
    OUTCOME
  FROM BPHADMIN.BLACKLIST ;
quit;
