CREATE OR REPLACE VIEW BPHADMIN.AMREPORTBLOCKDETAIL(REPORTBLOCKDETAILKEY, REPORTBLOCKHEADERKEY, BODYTYPE, LINESEQUENCE, BLOCKSEQUENCE, VERSION, WHENMODIFIED)
AS
  SELECT REPORTBLOCKDETAILKEY,
    REPORTBLOCKHEADERKEY,
    BODYTYPE,
    LINESEQUENCE,
    BLOCKSEQUENCE,
    VERSION,
    WHENMODIFIED
  FROM BPHADMIN.REPORTBLOCKDETAIL ;
/
quit;
