alter session set current_schema= "Z663303";
CREATE SYNONYM ACCOUNTPOSTING FOR  "BPHADMIN"."AMACCOUNTPOSTING";
 CREATE SYNONYM BLACKLIST FOR  "BPHADMIN"."AMBLACKLIST" ;
  CREATE SYNONYM BLACKLIST_D FOR  "BPHADMIN"."AMBLACKLIST_D";
  CREATE SYNONYM PAYMENTTRANSACTION FOR  "BPHADMIN"."AMPAYMENTTRANSACTION";
 CREATE SYNONYM REPORTBLOCKDETAIL FOR  "BPHADMIN"."AMREPORTBLOCKDETAIL";
alter session set current_schema='Z651358';
CREATE SYNONYM ACCOUNTPOSTING FOR  "BPHADMIN"."AMACCOUNTPOSTING";
 CREATE SYNONYM BLACKLIST FOR  "BPHADMIN"."AMBLACKLIST" ;
  CREATE SYNONYM BLACKLIST_D FOR  "BPHADMIN"."AMBLACKLIST_D";
  CREATE SYNONYM PAYMENTTRANSACTION FOR  "BPHADMIN"."AMPAYMENTTRANSACTION";
 CREATE SYNONYM REPORTBLOCKDETAIL FOR  "BPHADMIN"."AMREPORTBLOCKDETAIL";
alter session set current_schema='Z190207';
CREATE SYNONYM ACCOUNTPOSTING FOR  "BPHADMIN"."AMACCOUNTPOSTING";
 CREATE SYNONYM BLACKLIST FOR  "BPHADMIN"."AMBLACKLIST" ;
  CREATE SYNONYM BLACKLIST_D FOR  "BPHADMIN"."AMBLACKLIST_D";
  CREATE SYNONYM PAYMENTTRANSACTION FOR  "BPHADMIN"."AMPAYMENTTRANSACTION";
 CREATE SYNONYM REPORTBLOCKDETAIL FOR  "BPHADMIN"."AMREPORTBLOCKDETAIL";


  
